version: '3'

services:
  app:
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=<insert your host IP>
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    build: .
    command: /code/start-expo.sh
    volumes:
      - .:/code
    ports:
      - "19000:19000"
      - "19002:19002"
    
